data:
  train:
    indir: /content/lama_dataset/images
    # maskdir: /content/lama_real_masks/masks
    dataloader_kwargs:
      batch_size: 4
      num_workers: 2
      shuffle: true
  val:
    indir: /content/lama_dataset/images
    # maskdir: /content/lama_real_masks/masks
    dataloader_kwargs:
      batch_size: 4
      num_workers: 2
      shuffle: false
  visual_test: null

generator:
  kind: ffc_resnet
  input_nc: 4
  output_nc: 3
  ngf: 32
  n_downsampling: 3
  n_blocks: 8
  init_conv_kwargs:
    ratio_gin: 0.0
    ratio_gout: 0.75
  downsample_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
  out_ffc_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75

discriminator:
  kind: pix2pixhd_nlayer
  input_nc: 4
  ndf: 32
  n_layers: 3

losses:
  l1:
    kind: l1
    weight_known: 0
    weight_missing: 1
  adversarial:
    kind: r1
    weight: 10
    gp_coef: 0.001
    mask_as_fake_target: true
    allow_scale_mask: true
  perceptual:
    kind: perceptual
    weight: 0.05
  feature_matching:
    kind: feature_matching
    weight: 0.0

evaluator:
  kind: default_inpainted

training:
  epochs: 10
  save_interval: 1
  out_dir: /content/drive/MyDrive/lama_checkpoints

visualizer:
  kind: directory
  outdir: outputs/visualization

location:
  tb_dir: ./tb_logs

training_model:
  kind: default

trainer:
  kind: default
  kwargs:
    accelerator: gpu
    devices: 1
    max_epochs: 10
    precision: 32
    accumulate_grad_batches: 1
    gradient_clip_val: 0.0
    benchmark: true
    deterministic: false
    profiler: null
    log_every_n_steps: 50
    val_check_interval: 1.0
    num_sanity_val_steps: 0
    check_val_every_n_epoch: 1
    replace_sampler_ddp: true
  checkpoint_kwargs:
    monitor: val_loss
    save_top_k: 1
    mode: min
    save_last: true

optimizers:
  generator:
    kind: adam
    lr: 0.0001
    weight_decay: 0.0
  discriminator:
    kind: adam
    lr: 0.0001
    weight_decay: 0.0

schedulers:
  generator:
    kind: null
  discriminator:
    kind: null

augmentation:
  kind: null

callbacks: {}

mask_gen_kwargs:
  irregular_proba: 0.5
  irregular_kwargs:
    min_times: 2
    max_times: 20
    max_width: 80
    max_angle: 6
    max_len: 200
  box_proba: 0.3
  box_kwargs:
    margin: 0
    bbox_min_size: 10
    bbox_max_size: 200
    max_times: 5
    min_times: 1
  ellipse_proba: 0.2
  ellipse_kwargs:
    min_axis: 10
    max_axis: 120
    min_times: 1
    max_times: 3
  squares_proba: 0
  segm_proba: 0