data:
  train:
    kind: default
    root_dir: /content/lama_dataset
    img_suffix: .png
    mask_suffix: .png
    img_dir: images
    mask_dir: masks
  val:
    kind: default
    root_dir: /content/lama_dataset
    img_suffix: .png
    mask_suffix: .png
    img_dir: images
    mask_dir: masks

generator:
  kind: ffc_resnet
  input_nc: 4
  output_nc: 3
  ngf: 32
  n_downsampling: 3
  n_blocks: 8
  init_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
  downsample_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
  resnet_conv_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75
  out_ffc_kwargs:
    ratio_gin: 0.75
    ratio_gout: 0.75

discriminator:
  kind: pix2pixhd_nlayer
  input_nc: 4
  ndf: 32
  n_layers: 3

losses:
  l1:
    kind: l1
    weight_known: 0
  adversarial:
    kind: r1
  perceptual:
    kind: perceptual
    weight: 0.05

evaluator:
  kind: default

training:
  batch_size: 4
  num_workers: 2
  lr: 0.0001
  epochs: 10
  save_interval: 1
  out_dir: /content/drive/MyDrive/lama_checkpoints

visualizer:
  kind: noop
  outdir: /content/lama/outputs/visualization

location:
  tb_dir: ./tb_logs

training_model:
  kind: default

trainer:
  kind: default
  kwargs:
    accelerator: gpu
    devices: 1
    max_epochs: 10
    precision: 32
    accumulate_grad_batches: 1
    gradient_clip_val: 0.0
    benchmark: true
    deterministic: false
    profiler: null
    log_every_n_steps: 50
    val_check_interval: 1.0
    num_sanity_val_steps: 0
    check_val_every_n_epoch: 1
    replace_sampler_ddp: true
  checkpoint_kwargs:
    monitor: val_loss
    save_top_k: 1
    mode: min
    save_last: true

optimizers:
  generator:
    kind: adam
    lr: 0.0001
    weight_decay: 0.0
  discriminator:
    kind: adam
    lr: 0.0001
    weight_decay: 0.0

schedulers:
  generator:
    kind: null
  discriminator:
    kind: null

augmentation:
  kind: null

callbacks: {}