generator_kind: random

mask_generator_kwargs:
  irregular_proba: 0.5
  irregular_kwargs:
    min_times: 2
    max_times: 20
    max_width: 80
    max_angle: 6
    max_len: 200

  box_proba: 0.3
  box_kwargs:
    margin: 0
    bbox_min_size: 10
    bbox_max_size: 200
    max_times: 5
    min_times: 1

  squares_proba: 0.1
  segm_proba: 0.1

  # ellipse_proba: 0.1  # Для будущей поддержки эллипсов
  # ellipse_kwargs:
  #   min_axis: 10
  #   max_axis: 150
  #   max_times: 3
  #   min_times: 1

  variants_n: 7

  # mask_circle_limit: true  # Для будущего ограничения по кругу
  # circle_margin: 0.01

max_masks_per_image: 2

cropping:
  out_min_size: 512
  handle_small_mode: upscale
  out_square_crop: True
  crop_min_overlap: 1

max_tamper_area: 0.7
